# Generated by Django 4.0.4 on 2022-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
    ]
