# Generated by Django 4.0.4 on 2022-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, default=0, related_name='related_cart', to='mainapp.cartitem', verbose_name='Товары в корзине'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
