# Generated by Django 4.0.4 on 2022-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_cart_products_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sale_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена товара в момент покупки'),
        ),
    ]
