# Generated by Django 4.0.4 on 2022-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_cartitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
