# Generated by Django 4.0.4 on 2022-05-16 05:19

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_product_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(upload_to=mainapp.models.upload_image_function, verbose_name='Лого производителя'),
        ),
    ]
