# Generated by Django 4.0.4 on 2022-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features_app', '0001_initial'),
        ('mainapp', '0010_alter_images_image_alter_manufacturer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='all_images',
            field=models.ManyToManyField(to='mainapp.images', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='features_app.feature', verbose_name='Характеристики'),
        ),
    ]
