# Generated by Django 4.0.4 on 2022-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_images_product_images_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название товара'),
        ),
    ]
