# Generated by Django 4.0.4 on 2022-05-18 06:49

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=mainapp.models.upload_image_function, verbose_name='Изображения'),
        ),
    ]
