# Generated by Django 4.0.4 on 2022-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='all_images',
            field=models.ManyToManyField(blank=True, to='mainapp.images', verbose_name='Галерея изображений'),
        ),
    ]
