# Generated by Django 4.0.4 on 2022-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_customer_address_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
