# Generated by Django 4.0.4 on 2022-05-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_cart_for_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.AddField(
            model_name='images',
            name='phone',
            field=models.ForeignKey(default=6, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
