# Generated by Django 4.0.4 on 2022-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_images_title_images_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_staff', to='mainapp.order', verbose_name='Заказы покупателя'),
        ),
    ]
