# Generated by Django 4.0.4 on 2022-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features_app', '0003_alter_feature_name'),
        ('mainapp', '0020_alter_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='features_app.feature', verbose_name='Характеристики'),
        ),
    ]
