# Generated by Django 4.0.4 on 2022-05-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features_app', '0002_alter_feature_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название характеристики'),
        ),
    ]
